### PR TITLE
Add vanilla powershell rendition

### PR DESCRIPTION
**Pull request by KodySalak**
Added a vanilla powershell script to grab the cert/key and import it into the windows certificate store.

### CODE REVIEW

**Comment by gregtwallace** [comment]
Looks good and worked on my machine. Couple feedback points:

- On the openssl command, I had to make `pkcs12` lower case otherwise it would error with `Invalid command 'PKCS12'; type "help" for a list.`.  
- "C:\Program Files\OpenSSL-Win64\bin\openssl.exe" is the default install path, it is probably better to assume that for the example.
- I think using a subfolder in the Windows default temp would be better for the example. Also, ideally the path would be removed after the script is done.
- In the new version I'm building now, LeGo will have `/legocerthub` as the first piece of the API path.  Please add to this. (see: https://github.com/gregtwallace/certificate-scripts/commit/7e963caf73e80410d36b40b1638fd40879d63d52)

**Comment by KodySalak** [comment]
Alrighty, made those changes. 

- pkcs12
- made the OpenSSL path a variable and changed it's path
- using C:\Windows\Temp\tempcerts as the temp path
- added legocerthub/ to the API paths.

**Comment by gregtwallace** [comment]
I made some tweaks and then reworked the script logic to prevent expiration.  It compares the expiration of the LeGo cert vs. machine cert, rather than waiting until the machine cert actually expires.

I added a command to remove the old cert also.  I have no idea what the use case for this is.  My concern is that removing of the old cert and adding the new one won't update whatever applications are using the cert and problems may occur.  What are you using this for?  Can you test and/or further modify to address that concern?

**Comment by KodySalak** [comment]
Thank you for your changes, I really appreciate it.

> I added a command to remove the old cert also.

~~Can you tell me what line I'm looking for? I don't see anything in the most recent commit that shows any new deletions other than the tempcerts directory after it's done~~ Found it - sorry.

My thought process with that was to remove it to prevent the script for getting angry about more than one cert being selected from my `$CurrentCertExpireTime` variable on it's next run, since I'm selecting based on the name. I will try to think of a way to select the "newest-cert-about-to-expire" and write that, but for now I really can't think of a way to cleanly do it.

**Comment by KodySalak** [comment]
Got it! Let me know if that will work for you.

**Comment by gregtwallace** [comment]
I'm fine with this.  I'm still curious about how this would work practically with a real service but since I don't have any to play with I'll just leave that to other folks to modify further as they see fit :)

Thanks for the contribution.

**Pull request merged**
